# Chats that led me here: https://dapphub.chat/channel/dev?msg=SjN9jmkiXFuKaFqWM and https://dapphub.chat/channel/dev?msg=HnZi8PHXquyzZ35cX
# So based it off of: https://github.com/centrifuge/tinlake-maker-lib/blob/c47b6e1b17e3e3d58036ad7356bec34370edccd4/.github/workflows/build.yml

name: "Dapptools CI"
on:
    push:
        branches: [Version-1.1, Version-2]
    pull_request:
        branches: ["*"]
jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
                # we need this to map platform names as used by github to
                # the attribute names defined in release.nix
                include:
                    - os: ubuntu-latest
                      os_attr: linux
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Checkout submodules
              run: git submodule update --init --recursive
            - uses: cachix/install-nix-action@v14
            - uses: cachix/cachix-action@v10
              with:
                  name: dapp
                  skipPush: true
                  signingKey: ""
            - name: install
              run: nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_7_5
            - name: test
              # 1.  They used 'make test' instead which referenced a Makefile https://github.com/centrifuge/tinlake-maker-lib/blob/master/Makefile   I'm not sure if we need that so just doing this instead
              # 2.  Had to add 'export LANG=C.UTF-8' as per recommendation from https://stackoverflow.com/questions/63746826/what-might-cause-commitandreleasebuffer-invalid-argument-invalid-character
              run: nix-shell --pure --command "export LANG=C.UTF-8 ; dapp test"
